# Generated by Django 5.2.3 on 2025-06-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConsultationReques",
            new_name="ConsultationRequest",
        ),
    ]
